Add logging and tests and build using mvn
An initial version of adding logs to chameleon
An initial version of adding specs (tests) to chameleon.
Adding pom.xml so the project can be build using maven.

Issue-ID: AAI-1220
Change-Id: I85f46fd7f625c83b84f211d6766970431e6d91eb
Signed-off-by: Shwetank Dave <shwetank.dave@amdocs.com>

diff --git a/devops/chameleon/build-chameleon b/devops/chameleon/build-chameleon
--- a/devops/chameleon/build-chameleon
+++ b/devops/chameleon/build-chameleon
@@ -1,2 +1,13 @@
-lein uberjar
-cp -f ../../target/chameleon.jar .
+!#/bin/bash
+ls build-chameleon
+if [ $? -eq 0 ]; then
+    echo "Building Chameleon"
+else
+    echo "FAILED. Make sure you're in the same directory as the \"build-chameleon\" file."
+    exit 1
+fi
+pushd .
+cd ../../
+mvn -X clean package
+popd
+cp -f ../../target/chameleon-0.1.0-fat-jar.jar ./chameleon.jar
